### ISSUE TITLE
Data Downloader

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Lean.Brokerages.ByBit#20]
- Review data downloader so it fits the expected pattern and behavior following other brokerage implementations:
      - The downloader should be able to be initialized by the composer, see error below 
      - ...
```
Error Message:
 ---> System.MissingMethodException: Cannot dynamically create an instance of type 'QuantConnect.Brokerages.Bybit.ToolBox.BybitBrokerageDownloader'. Reason: No parameterless constructor
defined.
   at System.RuntimeType.ActivatorCache..ctor(RuntimeType rt)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at QuantConnect.Util.Composer.GetExportedValueByTypeName[T](String typeName, Boolean forceTypeNameOnExisting) in
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Common/Util/Composer.cs:line 290
   at QuantConnect.Lean.Engine.DataFeeds.DownloaderDataProvider..ctor() in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/DataFeeds/DownloaderDataProvider.cs:line 57
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at QuantConnect.Util.Composer.GetExportedValueByTypeName[T](String typeName, Boolean forceTypeNameOnExisting) in
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Common/Util/Composer.cs:line 290
   at QuantConnect.Lean.Engine.LeanEngineAlgorithmHandlers.FromConfiguration(Composer composer, Boolean researchMode) in
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/LeanEngineAlgorithmHandlers.cs:line 208
```

**Comment by Martin-Molinero** [comment]
Potential work around for lean cli, using `--data-provider-historical local` in the live deploy command
